# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sperical_Studio_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(838, 617)
        Form.setMinimumSize(QtCore.QSize(769, 544))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageicono = QtWidgets.QLabel(self.groupBox)
        self.imageicono.setText("")
        self.imageicono.setObjectName("imageicono")
        self.verticalLayout.addWidget(self.imageicono)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.densityGraph = QtWidgets.QRadioButton(self.groupBox)
        self.densityGraph.setChecked(True)
        self.densityGraph.setObjectName("densityGraph")
        self.verticalLayout_2.addWidget(self.densityGraph)
        self.angledistribution = QtWidgets.QRadioButton(self.groupBox)
        self.angledistribution.setObjectName("angledistribution")
        self.verticalLayout_2.addWidget(self.angledistribution)
        self.vectorgraph = QtWidgets.QRadioButton(self.groupBox)
        self.vectorgraph.setObjectName("vectorgraph")
        self.verticalLayout_2.addWidget(self.vectorgraph)
        self.modstats = QtWidgets.QRadioButton(self.groupBox)
        self.modstats.setObjectName("modstats")
        self.verticalLayout_2.addWidget(self.modstats)
        self.angstats = QtWidgets.QRadioButton(self.groupBox)
        self.angstats.setObjectName("angstats")
        self.verticalLayout_2.addWidget(self.angstats)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.page)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.type3D = QtWidgets.QRadioButton(self.splitter_3)
        self.type3D.setObjectName("type3D")
        self.horizontalLayout_7.addWidget(self.splitter)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelX = QtWidgets.QLabel(Form)
        self.labelX.setEnabled(False)
        self.labelX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelX.setObjectName("labelX")
        self.horizontalLayout_3.addWidget(self.labelX)
        self.comboBoxX = QtWidgets.QComboBox(Form)
        self.comboBoxX.setObjectName("comboBoxX")
        self.horizontalLayout_3.addWidget(self.comboBoxX)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelY = QtWidgets.QLabel(Form)
        self.labelY.setEnabled(False)
        self.labelY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelY.setObjectName("labelY")
        self.horizontalLayout_4.addWidget(self.labelY)
        self.comboBoxY = QtWidgets.QComboBox(Form)
        self.comboBoxY.setObjectName("comboBoxY")
        self.horizontalLayout_4.addWidget(self.comboBoxY)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.labelZ = QtWidgets.QLabel(Form)
        self.labelZ.setEnabled(False)
        self.labelZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelZ.setObjectName("labelZ")
        self.horizontalLayout_6.addWidget(self.labelZ)
        self.comboBoxZ = QtWidgets.QComboBox(Form)
        self.comboBoxZ.setObjectName("comboBoxZ")
        self.horizontalLayout_6.addWidget(self.comboBoxZ)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.calculate = QtWidgets.QPushButton(Form)
        self.calculate.setEnabled(False)
        self.calculate.setObjectName("calculate")
        self.gridLayout.addWidget(self.calculate, 1, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonload = QtWidgets.QPushButton(Form)
        self.buttonload.setObjectName("buttonload")
        self.verticalLayout_4.addWidget(self.buttonload)
        self.buttonmap = QtWidgets.QPushButton(Form)
        self.buttonmap.setEnabled(False)
        self.buttonmap.setObjectName("buttonmap")
        self.verticalLayout_4.addWidget(self.buttonmap)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.Files = QtWidgets.QRadioButton(self.splitter_2)
        self.Files.setChecked(True)
        self.Files.setObjectName("Files")
        self.Map = QtWidgets.QRadioButton(self.splitter_2)
        self.Map.setObjectName("Map")
        self.verticalLayout_5.addWidget(self.splitter_2)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sperical Studio"))
        self.groupBox.setTitle(_translate("Form", "            Sperical Statistics Studio"))
        self.densityGraph.setText(_translate("Form", "Density graph"))
        self.angledistribution.setText(_translate("Form", "Angle distribution"))
        self.vectorgraph.setText(_translate("Form", "Vector graph"))
        self.modstats.setText(_translate("Form", "Module stats"))
        self.angstats.setText(_translate("Form", "Angle stats"))
        self.type3D.setText(_translate("Form", "3d file"))
        self.labelX.setText(_translate("Form", "X"))
        self.labelY.setText(_translate("Form", "Y"))
        self.labelZ.setText(_translate("Form", "Z"))
        self.calculate.setText(_translate("Form", "Calculate"))
        self.buttonload.setText(_translate("Form", "Select file"))
        self.buttonmap.setText(_translate("Form", "Load Map"))
        self.Files.setText(_translate("Form", "Files"))
        self.Map.setText(_translate("Form", "Map"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
